version: "3"

services:
  postgres:
    image: postgres
    container_name: dbBank
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "bank"
