steps:
- name: Checkout code
  uses: actions/checkout@v2

- name: Set up JDK
  uses: actions/setup-java@v1
  with:
    java-version: 14

- name: Build with Maven
  run: mvn clean install

- name: Upload coverage to Codecov
  uses: codecov/codecov-action@v1
  with:
    fail_ci: true
    token: ${{ secrets.CODECOV_TOKEN }}
